canonical/craft-providers

- craft_providers/__init__.py
- craft_providers/executor.py
- docs/index.rst
> executor: introduce Executor abstract base class interface

- craft_providers/bases/buildd.py
- craft_providers/multipass/__init__.py
- craft_providers/multipass/_launch.py
- tests/integration/multipass/test_launch.py
- tests/unit/multipass/test_installer.py
- tests/unit/multipass/test_launch.py
> multipass: introduce launch to create and configure instances

- tests/integration/multipass/test_launch.py
> multipass tests: cleanup after launch tests

- craft_providers/lxd/__init__.py
- craft_providers/lxd/errors.py
- tests/unit/lxd/test_errors.py
> lxd: introduce errors module and LXDError

- craft_providers/lxd/__init__.py
- craft_providers/lxd/lxc.py
- tests/unit/lxd/test_lxc.py
To keep the size of the PR down, integration test will follow as a
separate PR, as it requires some additional helpers.
-----
> lxd: introduce LXC to interface with lxc

- craft_providers/lxd/__init__.py
- craft_providers/lxd/lxd_instance.py
- tests/integration/lxd/conftest.py
- tests/integration/lxd/test_lxc.py
- tests/integration/lxd/test_lxd_instance.py
- tests/unit/lxd/test_lxd_instance.py
- make `lxc` fixture available to all lxd integration tests.
- add unit & integration tests
-----
> lxd: introduce LXDInstance

- craft_providers/bases/buildd.py
- craft_providers/bases/instance_config.py
- craft_providers/executor.py
- craft_providers/lxd/lxd_instance.py
- craft_providers/multipass/multipass_instance.py
- tests/integration/lxd/test_launcher.py
- tests/integration/lxd/test_lxd_instance.py
- tests/integration/multipass/test_launch.py
- tests/integration/multipass/test_multipass_instance.py
- tests/unit/bases/test_buildd.py
- tests/unit/bases/test_instance_config.py
- tests/unit/conftest.py
- tests/unit/lxd/test_lxd_instance.py
- tests/unit/multipass/test_multipass_instance.py
Align with push/pull semantics for consistency.
-----
> executor: rename create_file() to push_file_io()

- craft_providers/bases/buildd.py
- tests/unit/bases/test_buildd.py
> buildd: drop udev requirement

- setup.py
> setup: pypi requires valid author email

- craft_providers/multipass/multipass.py
- requirements-dev.txt
- tests/integration/multipass/conftest.py
- tests/unit/conftest.py
- tests/unit/multipass/test_multipass.py
> pylint: uprev pylint and address new consider-using-with warnings

- tests/integration/conftest.py
- tests/integration/lxd/conftest.py
- tests/integration/lxd/test_launcher.py
- tests/integration/lxd/test_lxd_instance.py
- tests/integration/multipass/conftest.py
- tests/integration/multipass/test_launch.py
- tests/integration/multipass/test_multipass_instance.py
> integration tests: consolidate lxd/multipass fixtures for reuse

- .bumpversion.cfg
- setup.cfg
bumpversion will rewrite setup.cfg losing comments.
-----
> setup.cfg: split out bumpversion config

- .bumpversion.cfg
- craft_providers/__init__.py
- docs/conf.py
- setup.py
> version: bump to 1.0.0 (CRAFT-307)

- .github/workflows/tests.yaml
> CI: execute apt update prior to apt install

- .bumpversion.cfg
- craft_providers/__init__.py
- docs/conf.py
- setup.py
> Bump version: 1.0.0 → 1.0.1

- .bumpversion.cfg
- craft_providers/__init__.py
- docs/conf.py
- setup.py
> Bump version: 1.0.1 → 1.0.2

- craft_providers/lxd/installer.py
- craft_providers/lxd/lxd.py
- tests/integration/lxd/test_installer.py
- tests/unit/lxd/test_installer.py
While here, do a minor update for the error messages in
ensure_lxd_is_ready() to meet the CLI guidelines.
-----
> lxd: account for minimum required version in checks (CRAFT-437)

- Makefile
Signed-off-by: Sergio Schvezov <sergio.schvezov@canonical.com>
-----
> make: clean up help for freeze-requirements

- .bumpversion.cfg
- craft_providers/__init__.py
- docs/conf.py
- setup.py
> Bump version: 1.0.2 → 1.0.3 (CRAFT-457)

- README.md
Complement the README file with directions on how to run tests, freeze
requirements and generate documentation locally. General commit message
guidelines also added.
Co-authored-by: Sergio Schvezov <sergio.schvezov@canonical.com>
Signed-off-by: Claudio Matsuoka <claudio.matsuoka@canonical.com>
-----
> docs: add additional info to readme

- .github/workflows/tests.yaml
- tox.ini
This is a more complex project, so to start simple and ensure things
keep working with tox the first item to be replaced are the unit
tests.
Fixes #84
Signed-off-by: Sergio Schvezov <sergio.schvezov@canonical.com>
-------
> # tox: fix broken dependency on requirements.txt

- Makefile
- craft_providers/lxd/lxc.py
- craft_providers/multipass/multipass.py
Also improved Makefile to be explicit about what to test in each case.
> Fixed new pyright issues.

- .bumpversion.cfg
- craft_providers/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
* Export public API names
* Declare instance paths as PurePath
* Address linter issues
* Update documentation
-----
> Release 1.0.4

- .bumpversion.cfg
- craft_providers/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
* Refactor instance configuration
* Disable automatic apt actions in instance setup
* Warm-start existing instances instead of rerunning full setup
* Don't reinstall snaps already installed on target
-----
> Release 1.2.0

- craft_providers/executor.py
- craft_providers/lxd/lxd_instance.py
- craft_providers/multipass/multipass_instance.py
The methods actually not only create files, but when the file already
exists for the given path, they replace the files.
-----
> docs: Update docstrings for `push_file_io` methods

- .bumpversion.cfg
- craft_providers/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
* Refactor snap injection logic
* Always check multipass command execution results
* Update tests and documentation
-----
> Release 1.3.0

- .bumpversion.cfg
- craft_providers/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
-----
- Add stdin parameter for LXC commands (default: null)
> Release 1.3.1

- craft_providers/executor.py
- tests/unit/test_executor.py
> Pull file from the environment into a temporary file in the host (CRAFT-1224).

- craft_providers/executor.py
- craft_providers/multipass/multipass_instance.py
- tests/unit/conftest.py
Similar to https://github.com/canonical/craft-providers/pull/83, but I
missed a few extra places that are needed in order for type-checking to
work properly in consumers.
-----
> Declare more instance paths as PurePath

- craft_providers/bases/buildd.py
- tests/unit/bases/test_buildd.py
-----
New parameter in `BuilddBase` class that installs system packages in the base.
I manually tested with `snapcraft` and it appears to be 100% compatible.  Currently, `snapcraft` is the only application installing additional system packages.
Similar to https://github.com/canonical/craft-providers/pull/137.
(CRAFT-1223)
> base: add optional list of system packages to install

- .bumpversion.cfg
- craft_providers/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
> Bump version: 1.3.1 → 1.4.0

- .bumpversion.cfg
- craft_providers/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
> Bump version: 1.4.1 → 1.4.2

- craft_providers/lxd/remotes.py
- tests/unit/lxd/test_remotes.py
> Avoid remote adding race condition with other processes (CRAFT-1043).

- craft_providers/lxd/errors.py
- craft_providers/lxd/installer.py
- tests/integration/lxd/test_installer.py
- tests/unit/lxd/test_errors.py
- tests/unit/lxd/test_installer.py
-----
1. Consolidate duplicate error messages into one location.
2. Add help message to other errors.
> lxd: improve error messages

- .bumpversion.cfg
- craft_providers/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
> Bump version: 1.5.1 → 1.6.0

- .bumpversion.cfg
- craft_providers/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
> Bump version: 1.6.0 → 1.6.1

- tests/integration/lxd/test_launcher.py
- tests/integration/lxd/test_remotes.py
- tests/integration/multipass/test_launch.py
-----
Resolves https://github.com/canonical/craft-providers/issues/108.
> tests: test ubuntu 22.04 images

- .bumpversion.cfg
- craft_providers/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
> Bump version: 1.6.1 → 1.6.2

- .bumpversion.cfg
- craft_providers/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
> Bump version: 1.6.2 → 1.7.0

- craft_providers/bases/buildd.py
- tests/unit/bases/test_buildd.py
> buildd: add try/except block for snap refresh commands

- .bumpversion.cfg
- craft_providers/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
> Bump version: 1.7.0 → 1.7.1

- tests/unit/lxd/test_lxc.py
-----
Minor test improvement suggested by @lengau.
> tests: use `assert_called_once_with`

- .bumpversion.cfg
- craft_providers/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
-----
Small release for checking LXD id maps on existing instances.
> Bump version: 1.7.1 → 1.7.2

- tests/integration/lxd/test_launcher.py
-----
Follow up from https://github.com/canonical/craft-providers/pull/205#discussion_r1092511264
> tests: split lxd integration tests

- craft_providers/lxd/lxc.py
-----
I recently brought a file under 1,000 LOC, so the pylint suppression can be removed.
> lint: remove pylint useless suppression "too-many-lines"

- README.md
> readme: update readthedocs link

- .bumpversion.cfg
- craft_providers/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
> Bump version: 1.7.2 → 1.8.0

- .bumpversion.cfg
- craft_providers/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
> Bump version: 1.8.1 → 1.9.0

- .bumpversion.cfg
- craft_providers/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
> Bump version: 1.9.0 → 1.10.0

- craft_providers/base.py
- craft_providers/bases/__init__.py
- craft_providers/bases/errors.py
- craft_providers/bases/instance_config.py
- craft_providers/bases/ubuntu.py
- craft_providers/errors.py
- craft_providers/lxd/lxd_provider.py
- craft_providers/lxd/remotes.py
- craft_providers/multipass/multipass_provider.py
- tests/integration/conftest.py
- tests/integration/lxd/test_launcher.py
- tests/integration/lxd/test_lxd_provider.py
- tests/integration/lxd/test_remotes.py
- tests/integration/multipass/test_launch.py
- tests/integration/multipass/test_multipass_provider.py
- tests/unit/bases/test_errors.py
- tests/unit/bases/test_instance_config.py
- tests/unit/bases/test_ubuntu_buildd.py
- tests/unit/lxd/test_lxd_provider.py
- tests/unit/lxd/test_remotes.py
- tests/unit/multipass/test_multipass_provider.py
Prepare for additional OS support.
> bases: refactor buildd to ubuntu

- craft_providers/actions/snap_installer.py
- tests/integration/actions/test_snap_installer.py
- tests/unit/actions/test_snap_installer.py
-----
When installing a snap in an instance, do not use the snap name suffix (if present) when installing from the store, in temporary filenames, or in the instance config file.
This is a bug fix following up on CRAFT-1660, where the instance config files were not trimming the snap name suffix:
Previous `/etc/craft-instance.conf`:
```
compatibility_tag: snapcraft-buildd-base-v0.0
snaps:
snapcraft:
revision: '8931'
source: host
snapcraft_foo:
revision: '8928'
source: host
snapcraft_bar:
revision: '8931'
source: host
```
New `/etc/craft-instance.conf`:
```
snaps:
snapcraft:
revision: '8931'
source: host
```
> snap_installer: trim suffix from snap names

- craft_providers/lxd/lxd_instance.py
> tests: workaround mypy bug 15031

- craft_providers/provider.py
-----
`allow_unstable` parameter defaults to False.
> provider: add default for launched_environment parameter

- .bumpversion.cfg
- craft_providers/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
> Bump version: 1.10.0 → 1.11.0

- setup.py
-----
This is the same as craft-parts: https://github.com/canonical/craft-parts/pull/440
> deps: pin urllib3 to v1.x

- craft_providers/multipass/multipass_instance.py
-----
Refactor `push_file_io()`.  No functional changes.
I moved a block of code out of `push_file_io()` to `_create_temp_file()`, so I can reuse it in `push_file()` in a subsequent PR.
(CRAFT-1719)
> multipass(MultipassInstance): refactor push_file_io

- .bumpversion.cfg
- craft_providers/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
-----
1.12.0 (2023-05-18)
-------------------
- Add AlmaLinux 9 base
- Add stricter typing for base names
- Refactor CI workflow
- Refactor Multipass `push_file_io`
- Pin dependency urllib3<2
> Bump version: 1.11.0 → 1.12.0

- craft_providers/lxd/lxd_instance.py
- tests/integration/lxd/test_lxd_instance.py
- tests/unit/lxd/test_lxd_instance.py
> lxd: make push_file_io work on newer Ubuntu versions

- .github/workflows/tests.yaml
> ci: future-proofing Python tests

- .bumpversion.cfg
- craft_providers/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
> Bump version: 1.12.0 → 1.13.0

- .pre-commit-config.yaml
-----
Add `pre-commit` from starbase.
This builds on top of https://github.com/canonical/craft-providers/pull/291, so only the last commit needs review here.
See https://github.com/canonical/craft-providers/issues/287.
(CRAFT-1726)
> ci: add pre-commit config

- craft_providers/base.py
- craft_providers/lxd/launcher.py
- craft_providers/util/os_release.py
- pyproject.toml
-----
Resolves:
- `SIM102`: Use a single `if` statement instead of nested `if` statements
- `SIM114`: Combine `if` branches using logical `or` operator
> lint: fix ruff warnings SIM102 and SIM114

- .github/release-drafter.yml
- .github/workflows/cla-check.yaml
- .github/workflows/release-drafter.yaml
- .github/workflows/tests.yaml
- craft_providers/__init__.py
- docs/reference/index.rst
- pyproject.toml
- tests/integration/test_version.py
- tox.ini
-----
Merge `starbase` into craft-providers.  It ended up being a smooth and easy merge!
> :warning: ** Do not squash! **
(CRAFT-1726)
> starbase: merge 'starbase/main'

- pyproject.toml
-----
Now that the starbase merge is complete (#287), I created new issues for linting (#325) and typing (#326).
(CRAFT-1726)
> ci: update comments for linting and typing issues

- pyproject.toml
- tests/integration/conftest.py
- tests/integration/lxd/test_lxd.py
- tox.ini
> tests: add a sudo marker for integration tests that require sudo

- tox.ini
> tox: improve UX for testing

- tests/integration/lxd/test_launcher.py
-----
Minor refactor. Prerequisite for CRAFT-1767.
> tests: use fixture for base_configuration

- craft_providers/lxd/lxd.py
- craft_providers/multipass/multipass.py
- pyproject.toml
> meta: remove deprecated pkg_resources usages

- docs/changelog.rst
> docs: update changelog for 1.14.0

- .bumpversion.cfg
- craft_providers/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
-----
Old branch so this follows the old release/versioning process.
> Bump version: 1.10.0 → 1.10.1

- pyproject.toml
-----
Pydantic v2 [broke](https://github.com/canonical/craft-providers/actions/runs/5425485846/jobs/9866285742#step:7:64) some tests.  I'm freezing the library for now.
> requirements: freeze pydantic<2.0

- craft_providers/lxd/lxc.py
- tests/unit/lxd/test_lxc.py
To avoid race when multiple caller try to create same project.
CRAFT-1849
> lxc: recheck when creating project failed

- docs/changelog.rst
- pyproject.toml
* Prevent race when two processes try to create the same project at the same time
-----
> Release 1.14.1

- docs/changelog.rst
Merge hotfix/1.14.1 back into main.
-----
> Merge 1.14.1

- .github/renovate.json5
> deps: fix renovate scheduler

- craft_providers/lxd/launcher.py
- tests/integration/lxd/test_launcher.py
- tests/unit/lxd/test_launcher.py
-----
Set the timezone in the instance to match the host's timezone:
``` shell
2023-07-28 14:46:55.993 :: 2023-07-28 19:46:53.590 Executing action
2023-07-28 14:53:30.029 :: 2023-07-28 14:53:28.061 Executing action
```
Originally, I tried calling `timedatectl set-timezone` in the instance.  This was not a reliable experience - the integration tests intermittently failed with `Failed to create bus connection: No such file or directory` on the `buildd` images.
Perhaps someone with more `dbus` expertise could weigh in here, but I couldn't figure out the root cause.
After struggling with `timedatectl`, I followed Simos's [advice on the LXD forum](https://discuss.linuxcontainers.org/t/howto-set-the-timezone-in-lxd-containers/876) and set the `TZ` environment variable in the instance's config. …
> lxd: set timezone of instance to match host's timezone

- README.rst
- craft_providers/lxd/errors.py
- craft_providers/lxd/lxd_instance.py
- docs/explanation/index.rst
- tests/integration/lxd/test_installer.py
- tests/unit/lxd/test_errors.py
- tests/unit/lxd/test_installer.py
-----
The LXD project is no longer part of the LinuxContainers project but can now be found directly on Canonical's websites.
See the announcement here: https://linuxcontainers.org/lxd/
>  lxd: update links from linuxcontainers.org to ubuntu.com

- tests/unit/bases/test_almalinux.py
- tests/unit/bases/test_centos_7.py
- tests/unit/bases/test_ubuntu_buildd.py
- tests/unit/conftest.py
- tests/unit/test_base.py
-----
Some minor test refactoring in preparation for #184.
(CRAFT-1984)
> tests: refactor verify_network and DEFAULT_FAKE_CMD usage

- .github/workflows/release-publish.yaml
-----
Add release publishing workflow from starbase.
Resolves #361
> ci: add release publishing workflow

- docs/changelog.rst
> docs: update changelog for 1.15.0

- craft_providers/actions/snap_installer.py
- craft_providers/base.py
- tests/unit/actions/test_snap_installer.py
For helps understanding error or debug.
Fix: https://github.com/canonical/craft-providers/issues/396
> fix: add snap commands logging

- craft_providers/base.py
- craft_providers/bases/__init__.py
- craft_providers/bases/almalinux.py
- craft_providers/bases/centos.py
- craft_providers/bases/ubuntu.py
- craft_providers/lxd/launcher.py
- craft_providers/lxd/lxd_provider.py
- craft_providers/multipass/multipass_provider.py
- tests/integration/lxd/conftest.py
- tests/integration/lxd/test_launcher.py
- tests/integration/lxd/test_lxc.py
- tests/integration/lxd/test_lxd_provider.py
- tests/integration/multipass/test_multipass_provider.py
- tests/unit/bases/test_almalinux.py
- tests/unit/bases/test_centos_7.py
- tests/unit/bases/test_ubuntu_buildd.py
- tests/unit/lxd/test_launcher.py
- tests/unit/test_base.py
> feat(base): cache pip directory

- docs/changelog.rst
> docs(changelog): add 1.17.0 release notes

- README.rst
-----
Make the summary more assertive.
> docs(readme): reword summary

- docs/changelog.rst
> docs(changelog): add 1.18.0 release notes

- .github/CODEOWNERS
-----
Prerequisite to use self-hosted runners.
Unblocks #330.
> ci(github): add starcraft team as codeowners

- craft_providers/bases/__init__.py
- craft_providers/bases/ubuntu.py
- craft_providers/lxd/remotes.py
- craft_providers/multipass/multipass_provider.py
- tests/integration/multipass/test_multipass_provider.py
> feat(buildd): add support for ubuntu 23.10

- docs/.custom_wordlist.txt
- docs/changelog.rst
> docs(changelog): add 1.19.0 release notes

- docs/changelog.rst
> docs(changelog): add 1.19.1 release notes

- docs/index.rst
> docs: update code of conduct link

- docs/changelog.rst
> docs(changelog): add 1.19.2 release notes

- docs/changelog.rst
> docs(changelog): add 1.20.0 release notes

- README.rst
-----
Preview here: https://github.com/canonical/craft-providers/tree/readme-badges
> docs(readme): add weekly test and code coverage badges

- craft_providers/base.py
- tests/integration/lxd/test_launcher.py
- tests/integration/multipass/test_launch.py
- tests/unit/bases/test_almalinux.py
- tests/unit/bases/test_centos_7.py
- tests/unit/bases/test_ubuntu_buildd.py
- tests/unit/test_base.py
-----
Blocked by #473
Planning to `rebase and merge` to expedite the hotfix release (hence the force-push).
> chore(bases): bump compatibility tag to v5

- craft_providers/base.py
- craft_providers/lxd/launcher.py
- docs/changelog.rst
- tests/integration/lxd/test_launcher.py
- tests/integration/multipass/test_launch.py
- tests/unit/bases/test_almalinux.py
- tests/unit/bases/test_centos_7.py
- tests/unit/bases/test_ubuntu_buildd.py
- tests/unit/lxd/test_launcher.py
- tests/unit/test_base.py
> chore: merge hotfix/1.19

- craft_providers/base.py
- craft_providers/lxd/launcher.py
- docs/changelog.rst
- tests/integration/lxd/test_launcher.py
- tests/integration/multipass/test_launch.py
- tests/unit/bases/test_almalinux.py
- tests/unit/bases/test_centos_7.py
- tests/unit/bases/test_ubuntu_buildd.py
- tests/unit/lxd/test_launcher.py
- tests/unit/test_base.py
-----
Second attempt of #477, which was reverted because I accidentally squash-merged the PR.
> chore: merge hotfix/1.19 

- .github/renovate.json5
> ci(deps): have renovate ignore use patterns rather than full names.

- docs/changelog.rst
> docs(changelog): add 1.21.0 release notes

- docs/changelog.rst
-----
Similar to #504, I will need @cmatsuoka to override the CI failures for alma linux (#502).
> docs(changelog): add 1.22.0 release notes

- tests/integration/lxd/test_lxd_provider.py
-----
This can be re-enabled after #502 is resolved.
> test: disable almalinux integration tests

- pyproject.toml
> build: update ruff settings

- docs/changelog.rst
> docs(changelog): add 1.23.0 release notes

- .github/renovate.json5
-----
This package group was in the wrong section, causing renovate not to run
> ci: fix renovate config

- .github/renovate.json5
-----
Use the correct commit header for renovate commits.  Pulled in from starbase.
> ci: change renovate commit headers

- docs/.custom_wordlist.txt
- docs/changelog.rst
> docs(changelog): add 1.23.1 release notes

- docs/changelog.rst
> chore(merge): 'hotfix/1.20' into 'main'

- docs/changelog.rst
This reverts commit eea1f6237bd85a83ca6ce8e2db20dc6d3c5733bb.
I messed up and squash-merged instead of doing a real merge
-----
> chore(revert): revert "chore(merge): '1.20.3' into 'main' (#552)"

- docs/changelog.rst
> chore(merge): '1.20.3' into 'main'

- craft_providers/bases/__init__.py
- craft_providers/bases/ubuntu.py
- craft_providers/lxd/remotes.py
- craft_providers/multipass/multipass_provider.py
-----
Adding Oracular ASAP to stay ahead of any potential issues with 24.10.
> bases: add support for Ubuntu 24.10 (Oracular)

- pyproject.toml
-----
Same as https://github.com/canonical/craft-parts/pull/741
> build(deps): pin requests<2.32

- docs/changelog.rst
-----
Fixes #580 and will allow us to resolve [this TODO](https://github.com/canonical/craft-application/blob/11b4fff6c4cbb9dfb78720bb23bb9ddbaa6f614f/craft_application/models/project.py#L62) in craft-application
> docs(changelog): add 1.24.0 release notes

- craft_providers/errors.py
- craft_providers/lxd/installer.py
- docs/changelog.rst
- docs/explanation/index.rst
- pyproject.toml
- tests/unit/lxd/test_installer.py
The commits have been individually reviewed, with the exception of the latest one which has the new changelog entries.
> Merge `rockcraft` back into `main`

- docs/changelog.rst
> docs(changelog): add 1.25.0 release notes

- docs/changelog.rst
- pyproject.toml
- tests/integration/lxd/test_lxc.py
> chore: merge branch 'main' into 'feature/2.0'

- craft_providers/actions/snap_installer.py
- craft_providers/instance_config.py
> chore: cleanup pydantic warnings

- pyproject.toml
> build(deps): update pyright to 1.1.373

- craft_providers/bases/__init__.py
Where possible, we use more specific typing, but still fall back to the general typing used.
-----
> chore(type): improve typing for bases functions

- docs/reference/changelog.rst
> docs: add 2.0.0 entry to changelog

- docs/.custom_wordlist.txt
- docs/changelog.rst
> docs(changelog): add 1.24.2 release notes

- craft_providers/multipass/_launch.py
- craft_providers/multipass/multipass.py
- docs/.custom_wordlist.txt
- docs/reference/changelog.rst
- tests/integration/multipass/test_basic.py
- tests/unit/multipass/test_launch.py
-----
Merge 1.24.2 into `main`.
> chore(merge): 1.24.2 into main

- docs/reference/changelog.rst
- pyproject.toml
> build(deps): replace requests-unixsocket with requests-unixsocket2

- craft_providers/actions/snap_installer.py
- craft_providers/multipass/multipass.py
- docs/reference/changelog.rst
- pyproject.toml
- tests/unit/actions/test_snap_installer.py
- tests/unit/multipass/test_multipass.py
-----
I will merge `1.20.4` after this lands.
> chore(merge): 2.0.3 into main

- docs/reference/changelog.rst
-----
The same changes have been made on `hotfix/2.0`, so no changes needed besides the changelog.
> chore(merge): 1.20.4 into main

- .github/workflows/security-scan.yaml
- craft_providers/actions/snap_installer.py
- craft_providers/multipass/_launch.py
- craft_providers/multipass/multipass.py
- docs/.wordlist.txt
- docs/reference/changelog.rst
- pyproject.toml
- tests/integration/multipass/test_basic.py
- tests/unit/actions/test_snap_installer.py
- tests/unit/multipass/test_launch.py
- tests/unit/multipass/test_multipass.py
- tox.ini
-----
Merge main branch with feature/pro-source branch.
> chore: merge main branch with feature/pro-source branch

- craft_providers/base.py
- craft_providers/executor.py
- tests/unit/test_base.py
- [na] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
-----
Related bug: https://github.com/canonical/charmcraft/issues/2133
> Remove _ from hostnames

- craft_providers/base.py
- craft_providers/executor.py
- docs/reference/changelog.rst
- tests/unit/test_base.py
> chore(merge): 2.1.1 into main

- craft_providers/bases/checks.py
> style(auto): auto-format with ruff

- docs/.custom_wordlist.txt
- docs/explanation/cryptography.rst
- docs/explanation/index.rst
-----
Adds documentation on cryptographic technologies used in Craft Providers.
CRAFT-4395
> docs: add cryptographic documentation

- .pre-commit-config.yaml
- craft_providers/base.py
- craft_providers/bases/__init__.py
- craft_providers/bases/almalinux.py
- craft_providers/bases/centos.py
- craft_providers/bases/ubuntu.py
- craft_providers/errors.py
- craft_providers/lxd/lxd.py
- craft_providers/lxd/project.py
- craft_providers/multipass/multipass_instance.py
- craft_providers/util/env_cmd.py
- craft_providers/util/retry.py
- pyproject.toml
- tests/integration/lxd/conftest.py
- tests/integration/multipass/conftest.py
- tests/integration/test_hookutil.py
- tests/integration/test_version.py
- tests/unit/actions/test_snap_installer.py
- tests/unit/lxd/test_lxc.py
- tests/unit/multipass/test_multipass.py
- tests/unit/test_base.py
- tests/unit/util/test_retry.py
- tox.ini
> style: switch from black to ruff

- pyproject.toml
- tox.ini
This both updates mypy and switches to using pyright from the snap.
-----
> style: update type checkers

- craft_providers/bases/__init__.py
- craft_providers/bases/ubuntu.py
- craft_providers/lxd/remotes.py
- craft_providers/multipass/multipass_provider.py
- docs/reference/changelog.rst
- pyproject.toml
- tests/unit/lxd/test_remotes.py
-----
Adds support for Ubuntu 25.10 and preps a release.
> feat: add support for Ubuntu 25.10 (Questing)

- craft_providers/lxd/remotes.py
> remotes: use released images for noble and oracular

- docs/reference/changelog.rst
> docs: Release 2.4.0

- docs/reference/changelog.rst
> docs: Release 3.0.0
