canonical/craft-providers

.pylintrc, setup.cfg
Do not set a hard line limit.  Black will help autoformat,
but leave it to the author to determine if/when strings should
be broken up.
-----
=> pylint, flake: ignore line-too-long

.pylintrc, craft_providers/bases/__init__.py, craft_providers/bases/errors.py, craft_providers/bases/instance_config.py, requirements-dev.txt, requirements.txt, setup.cfg, setup.py, tests/unit/bases/test_instance_config.py
bases: introduce persistent in-instance datastore InstanceConfig
Enable Bases to persist a datastore that they can load on future use.
Initially, the only usage of this datastore is to track a "compatibility
tag", a simple mechanism in which a Base can ensure the instance to be
re-used is compatibile with the current Base.
- Add generic BaseConfigurationError() which will be used for base
configuration errors.
- Update requirements to add pydantic.
=> bases: introduce persistent in-instance datastore InstanceConfig

.github/workflows/tests.yaml, craft_providers/multipass/errors.py, craft_providers/multipass/installer.py, tests/integration/multipass/conftest.py, tests/integration/multipass/test_installer.py, tests/integration/multipass/test_multipass.py, tests/integration/multipass/test_multipass_instance.py, tests/unit/multipass/test_errors.py, tests/unit/multipass/test_installer.py
- Add MultipassInstallationError.
- Add unit tests for Multipass errors (formatting).
- Add unit & integration tests for installer bits.
- Update CI to allow MacOS integration tests to uninstall multipass.
-----
=> multipass: introduce installation support

craft_providers/bases/buildd.py, tests/unit/bases/test_buildd.py
When using sudo the PATH gets set to a cofigured secure_path, which is
not quite the same as the default found in /etc/environment. Redefine
default_command_environment() to be the combination of the two with the
secure path taking precendence.
By relying on this behavior, we can set /etc/environment and stop
setting the environment out for each command.
-----
=> buildd: take sudo secure_path into account for PATH

craft_providers/bases/__init__.py, craft_providers/bases/buildd.py, craft_providers/bases/errors.py, tests/unit/bases/test_buildd.py, tests/unit/bases/test_errors.py
- Introduce BaseCompatibilityError.
- Add tests for base errors.
=> buildd: introduce os compatibility checks

craft_providers/multipass/multipass.py
All callers specify check=, but better to require it than
to change the default.
=> multipass: doc fix and require check for Multipass._run()

craft_providers/bases/buildd.py, tests/unit/bases/test_buildd.py
buildd: add instance configuration & perform compatibility check
A compatibility tag will allow buildd to evolve in the future, providing
an interface to declare a subsequent update as incompatible with the old
one, forcing the user (or application) to clean the instance before
use.  It is possible that this may never increment if compatibility
is forever maintained, but since it cannot be guaranteed, we define this up
front with an extendable InstanceConfiguration for application-specific
customization.
Using class variables to allow application-specific extensions, read the                                           
instance configuration (if available) from /etc/craft-instance.conf using                       
InstanceConfiguration.
Set the compatibility tag to "buildd-base-v0" and …
=> buildd: add instance configuration & perform compatibility check

craft_providers/lxd/project.py, tests/integration/lxd/__init__.py, tests/integration/lxd/conftest.py, tests/integration/lxd/test_lxc.py, tests/unit/lxd/test_project.py
Add project project helpers.  With these helpers we can now add the lxc integration tets.
=> lxc: add project helpers and integration integration tests

craft_providers/lxd/lxd.py, tests/integration/lxd/test_lxd.py, tests/unit/lxd/test_lxd.py
Includes a `is_supported_version()` helper to ensure LXD version
meets minimum required version by craft-providers.
-----
=> lxd: introduce LXD for interacting with `lxd` command-line

docs/bases.rst, docs/conf.py, docs/executors.rst, docs/index.rst, requirements-dev.txt, setup.py
sphinx-pydantic is required because pydantic will break when
importing with TYPE_CHECKING.  The extension appears to work
around the issue, which would otherwise break most of the auto
generated documentation.
Add executors and bases documentation sections.
Re-freeze requirements.
-----
=> docs: update and fix doc generation

craft_providers/util/temp_paths.py, tests/unit/util/test_temp_paths.py
A few places need temp files/dirs and create them in the home directory
for Multipass to be able to access.
This adds two helpers to do this consistently:
- home_temporary_file()
- home_temporary_directory()
-----
=> util: add temp path helpers for creating temp paths in home directory

craft_providers/util/snap_cmd.py, tests/unit/util/test_snap_cmd.py
Add formulate_install_command() to return the snap install
with specified arguments.
-----
=> util: introduce snap_cmd module for snap command helpers

craft_providers/bases/buildd.py, tests/unit/bases/test_buildd.py
sudo and udev packages are required for LXD buildd images.
Subsequent PRs will include integration test coverage.
-----
=> buildd: install udev dependency for snapd (CRAFT-288)

craft_providers/lxd/lxd_instance.py, tests/unit/lxd/test_lxd_instance.py
This will remove the sudo dependency for LXD, which is not in
the LXD buildd images.
As using sudo populates the processes with /etc/environment,
a subsequent PR will will improve environment handling to
ensure consistency across providers.
-----
=> lxd instance: drop sudo usage (CRAFT-289)

craft_providers/lxd/__init__.py, craft_providers/lxd/remotes.py, tests/integration/lxd/test_remotes.py, tests/unit/lxd/test_remotes.py
Add configure_buildd_image_remote() helper to add the buildd
remote and return its name.  Calling applications will call
this as part of their setup code prior to launching
an instance.
Add launcher integration tests for the 16.04 and 18.04 buildd
images.  Xenial is currently unsupported because its
/etc/apt/sources.list does not include the -updates
or -security suites, breaking an assumption that snapd is updated
in the buildd image (it ships 2.0.2).  Further work will be
required to support it properly.
-----
Requires #54 and #53 for integration tests to pass.
=> lxd: add buildd remote support (CRAFT-260)

craft_providers/lxd/launcher.py, tests/integration/lxd/test_launcher.py, tests/unit/lxd/test_launcher.py
While LXD supported configuration of project & remote, the
launcher did not.  Extend launcher logic to support these.
Update unit tests and add integration test coverage.
-----
=> lxd launcher: enable configuration of project & remote (CRAFT-304)

craft_providers/lxd/launcher.py, tests/integration/lxd/conftest.py, tests/integration/lxd/test_launcher.py, tests/unit/lxd/test_launcher.py
Provide a simple toggle to automatically create the specified
LXD project if not found.  Defaults to False.
With this change, always verify the existence of the project
before continuing, raising LXDError() if not found.
-----
=> lxd launcher: add auto_create_project flag (CRAFT-150)

craft_providers/base.py, craft_providers/bases/buildd.py, craft_providers/lxd/launcher.py, craft_providers/lxd/lxd_instance.py, tests/unit/lxd/test_launcher.py, tests/unit/lxd/test_lxd_instance.py
When exec'ing a command through LXD, /etc/environment is not read in
by default as it was when previously using sudo. For now, extend
LXDInstance with the default command environment, which can be
overriden by the execute functions' env= parameter.
- Extend Base definition with 'environment' parameter already present
in BuilddBase.
- Move _rootify_lxc_command() into LXDInstance and account for the
default command environment.
- Update LXD launcher to set LXDInstance's environment from the
existing base configuration.  This way the environment will be
set for all executed commands.
Future work may change the mechanism used to set the environment
(such as using lxc configuration, or wrapper script).
-----
=> lxd instance: account for command environment (CRAFT-309)

craft_providers/bases/buildd.py, tests/unit/bases/test_buildd.py
apt update will return exit code 0 if it fails to fetch updates due to
networking issues.  This is problematic because it can silently fail
during use if networking is not available when running update.
Use the option APT::Update::Error-Mode="any" to catch any fetch failures
and exit with error.
-----
=> buildd base: configure apt to error on fetch failures (CRAFT-344)

craft_providers/lxd/__init__.py, craft_providers/lxd/installer.py, craft_providers/lxd/launcher.py, tests/integration/lxd/conftest.py, tests/integration/lxd/test_installer.py, tests/integration/lxd/test_launcher.py, tests/unit/lxd/test_installer.py, tests/unit/lxd/test_launcher.py
- Add is_initialized() method to installer module to check.
- Run this check when attempting to launch instance, raising an
LXDError on failure.
- Add unit and integration test coverage.
-----
=> lxd: check if LXD is initialized prior to launch (CRAFT-348)

craft_providers/lxd/__init__.py, craft_providers/lxd/installer.py, craft_providers/lxd/launcher.py, tests/integration/lxd/test_installer.py, tests/integration/lxd/test_launcher.py, tests/unit/lxd/test_installer.py, tests/unit/lxd/test_launcher.py
- Introduce is_user_permitted() to check if user has the necessary
permissions (that is, either root or in the lxd group).
- As the number of checks are increasing, add another interface
ensure_lxd_is_ready() which craft apps can use to verify the readiness
of LXD prior to use.
- Add permission check to LXD install to ensure user has necessary
permissions before continuing.
- Remove the initialization check from the launcher in favor of
using ensure_lxd_is_ready() to catch potential errors even earlier.
=> lxd: ensure user is permitted to use lxd (CRAFT-374)     

craft_providers/multipass/multipass.py, tests/integration/multipass/test_multipass.py, tests/unit/multipass/test_multipass.py
In preparation for multipass release, add interface for supported version and remove skipped test for multipass issue in now-unsupported versions.
=> multipass: is_supported_version() interface and require >=1.7

craft_providers/util/env_cmd.py, tests/unit/util/test_env_cmd.py
Extend env command wrapper with option for --chdir.
It is the caller's responsibility to ensure that the env command
supports chdir as older versions do not support it (Ubuntu 16.04).
-----
=> util/env_cmd: add support for --chdir (CRAFT-449)

craft_providers/executor.py, craft_providers/lxd/lxd_instance.py, craft_providers/multipass/multipass_instance.py, tests/integration/lxd/test_lxd_instance.py, tests/integration/multipass/test_multipass_instance.py, tests/unit/conftest.py, tests/unit/lxd/test_lxd_instance.py, tests/unit/multipass/test_multipass_instance.py
To support the use of `cwd` keyword arg for execute functions,
use env_cmd's chdir functionality.  This does not support all
OSs (works on 18.04+), but since it will otherwise fail
unexpectedly, this is a reasonable measure for the interim.
Applications needing support for older OSes can use their own
custom launcher script or avoid `cwd` altogether.
A better long term solution is to ask Multipass for additional
interfaces like --cwd <dir> (and --user <user> even) to match
what is available in LXD.
-----
=> multipass instance: use env's chdir for exec cwd (CRAFT-450)

craft_providers/multipass/__init__.py, craft_providers/multipass/_ready.py, tests/unit/multipass/test_ready.py
Add checks to ensure Multipass is ready for use similar to LXD's.
-----
=> multipass: introduce ensure_multipass_is_ready() (CRAFT-438)

.github/workflows/tests.yaml, tests/unit/util/test_env_cmd.py
Add Python 3.10 to GHA tests workflow ~~and tox~~.
Signed-off-by: Claudio Matsuoka <claudio.matsuoka@canonical.com>
-----
=> ci: add python 3.10 tests (CRAFT-745)

setup.py
Markdown was rendered as text as the content type was missing,
see https://packaging.python.org/en/latest/guides/making-a-pypi-friendly-readme/#including-your-readme-in-your-package-s-metadata
not necessary as I am an employee at Canonical
-----
=> Fix description rendering on PyPI

.pylintrc, craft_providers/lxd/launcher.py, craft_providers/lxd/lxd_instance.py, tests/integration/lxd/test_launcher.py, tests/unit/lxd/test_launcher.py
Instead of always using the running user's uid for id mapping, allow
the value to be passed by the application so that the uid of the host
directory owner can be used in situations where the two values are
different. Default to the current user's uid to keep compatibility
with existing behavior.
CRAFT-893, fixes #97
Signed-off-by: Claudio Matsuoka <claudio.matsuoka@canonical.com>
-----
=> lxd: pass id for host mount uid mapping

craft_providers/lxd/installer.py, tests/unit/lxd/test_installer.py
LXD doesn't always run as the `lxd` group as that is changeable
by the user (`snap set lxd daemon.group=adm`). As such, it is
better to check the socket to be writeable instead of hardcoding
a group.
=> lxd: in is_user_permitted() check if connecting to LXD works

Makefile, craft_providers/bases/buildd.py, craft_providers/bases/instance_config.py, craft_providers/util/temp_paths.py, tests/unit/bases/test_buildd.py, tests/unit/bases/test_instance_config.py, tests/unit/util/test_temp_paths.py
-----
This is a pre-requisite for CRAFT-970 (caching snap revision installed in an environment).
`instance_config.py` tightly encapsulated the `compatibility_tag` parameter and was not readily usable for storing other data.
Improvements from refactoring:
1. Snap revisions can now be stored in the config file.
2. An existing config can now be updated, instead of just overwriting.
3. `test` and `cat` subprocess commands replaced with `executor.pull_file()`
(CRAFT-969)
=> refactor: instance_config.py

craft_providers/bases/buildd.py, tests/unit/bases/test_buildd.py
Disable automatic APT work during the BuildBase instance setup, so any
explicitly specified APT operation (in the setup itself or later) will
not fail because any automatic work has the cache lock.
--
CRAFT-958
=> buildd: disable automatic APT in instance setup

craft_providers/base.py, craft_providers/bases/buildd.py, craft_providers/lxd/launcher.py, craft_providers/multipass/_launch.py, tests/unit/bases/test_buildd.py, tests/unit/lxd/test_launcher.py, tests/unit/multipass/test_launch.py
The full setup takes too long and is not needed, so I created a new warmup
method for when the instance already exists (and was fully setup in the
past).
=> buildd: just warm up already existing instances

setup.py
-----
Bump pylint to latest version, since `pylint-fixme-info` v1.0.3 was released.
The same change was applied to [craft-parts](https://github.com/canonical/craft-parts/commit/b2544d8fff7f0d8128174c717d5978f4fc6ad410#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7).
=> static: bump pylint to latest version

craft_providers/actions/snap_installer.py, craft_providers/bases/instance_config.py, tests/integration/actions/test_snap_installer.py, tests/unit/actions/test_snap_installer.py, tests/unit/bases/test_instance_config.py
-----
Cache snap revision in the target's `InstanceConfiguration`.
If the revision on the target matches the revision on the host, then the snap will not be re-injected or re-installed on the target.
- Snap is injected: **5.6 seconds**
- Store installed from store: **12.8 seconds**
- Snap injection/installation is skipped: **0.5 seconds**
These are informal results performed on a somewhat fast laptop.
I would expect an average charm developer to see build times cut by 5-15 seconds.
I ended up removing the `snap known` and `snap ack` calls from this PR.  I was struggling to get the code to work consistently and the unit testing was proving to be even more challenging.  
In retrospect, a better approach may have been to completely port over the data structures in …
=> actions: do not re-install same revision of snap on target

tests/integration/multipass/test_launch.py
core has been removed by multipass, craft-providers does not need to
support core so remove the test for it.
-----
=> tests: remove snapcraft:core

Makefile, craft_providers/actions/snap_installer.py, craft_providers/bases/buildd.py, craft_providers/util/snap_cmd.py, setup.py, tests/unit/actions/test_snap_installer.py, tests/unit/bases/test_buildd.py, tests/unit/conftest.py, tests/unit/util/test_snap_cmd.py
In detail:
- now `inject_from_store` actually *installs* or *refreshes* the snap directly from the store (no more download and local install); as a side effect, no longer is required to have `snapd` in the host for this operation.
- the situation of changing "from host" to/from "from store" is supported, un-installing the previous snap in that case
- improved (and tested) logs in `inject_from_host` and `inject_from_store`
- added `curl` to what is installed during instance setup (as it's needed to communicate to `snapd` in the target environment)
- some tests improved and made more explicit; lot of tests added to unit-test the helper functions
---
CRAFT-1068
=> snap installer: refactor installation logic

craft_providers/lxd/lxc.py, tests/unit/lxd/test_lxc.py
-----
Add `stdin` parameter to lxc's `subprocess` call.  Snapcraft 7 + core22 was hanging on github workflow using action-build.
Todo: Add unit tests for `_run_lxc`
Source: https://github.com/snapcore/action-build/issues/37
(CRAFT-1102)
=> lxc: add subprocess parameter for stdin

craft_providers/bases/buildd.py, tests/unit/bases/test_buildd.py
-----
This PR ensures that the `hostname` is valid, which was previously raising an error.
`BuilddBase`'s `hostname` parameter has similar naming conventions to [LXD instance names](https://github.com/canonical/craft-providers/pull/134).  Yet, the naming convention is different enough that I didn't combine the functionality between the two.
(CRAFT-1234)
=> bases: ensure BuilddBase hostname is valid

craft_providers/bases/buildd.py, tests/unit/bases/test_buildd.py
-----
New parameter in `BuilddBase` class that installs snaps in the base.
I created a pydantic model for each snap to be installed.  It gives the application lots of control over how the snap is installed.  For example, it is easy to specify a store channel or inject a snap from the host.
I manually tested this with 3 craft tools and it appears to be 100% compatible. (lpcraft wasn't tested, because it doesn't install any snaps)
- [usage in charmcraft](https://github.com/mr-cal/charmcraft/pull/1)
- [usage in rockcraft](https://github.com/mr-cal/rockcraft/pull/1)
- [usage in snapcraft](https://github.com/mr-cal/snapcraft/pull/1)
(CRAFT-1222)
=> base: add optional list of snaps to install

craft_providers/executor.py, tests/unit/conftest.py
-----
Add 2 functions, `exists()` and `delete()` to the `Executor` abstract base class.
This is required so applications can use these functions in the child classes.
(CRAFT-1251)
=> executor: add exists and delete function to abstract base class

craft_providers/lxd/launcher.py, craft_providers/lxd/lxd_instance.py, tests/integration/lxd/conftest.py, tests/integration/lxd/test_launcher.py, tests/integration/lxd/test_lxc.py, tests/integration/lxd/test_lxd_instance.py, tests/unit/lxd/test_launcher.py, tests/unit/lxd/test_lxd_instance.py
-----
The provided name for a LXD executor object is converted to comply with [LXD naming conventions](https://linuxcontainers.org/lxd/docs/master/instances/) for instances.
LXC has a 63 character limit on instance names.  [This snapcraft commit](https://github.com/snapcore/snapcraft/commit/21cb1ab9ae26cf3322356c190eb555ed05f2d498) adds 18-20 characters to the image name.  This is blocking snaps with long names from upgrading to core22.
Charmcraft has the [same issue](https://github.com/canonical/charmcraft/issues/629).
```
snapcraft-<project-name>-on-<build-on>-for-<build-for>-<project-path-inode>
└  10   ┘└   2 - 41     ┘└   8-11    ┘└    9-12       ┘└       10         ┘
```
Min size: 10 + 2 + 8 + 9 + 10 = 39
Max size: 10 + 41 + 11 + 12 + 10 = 84
``` …
```
=> lxd: use LXD-compatible instance names

craft_providers/bases/buildd.py, tests/unit/bases/test_buildd.py
-----
New optional parameter `compatibility_tag` for `BuilddBase`.
This allows applications to easily override the default compatibility tag without changing the existing behavior.
Manually tested and confirmed on all *craft applications!
(CRAFT-1248)
=> bases: allow overriding of compatibility tag

craft_providers/bases/buildd.py, tests/unit/bases/test_buildd.py
-----
I made a mistake in hostname validation logic!  
This fixes a bug where hostnames longer than 64 characters may not have trailing hyphens removed.
=> bases: fix bug in BuilddBase hostname validation logic

.bumpversion.cfg, craft_providers/__init__.py, docs/changelog.rst, docs/conf.py, setup.py
-----
This release for craft-providers 1.4.1 primarily addresses a bug in the truncation of long hostnames.
=> Bump version: 1.4.0 → 1.4.1

craft_providers/bases/buildd.py, tests/unit/bases/test_buildd.py
-----
If the environmental variables `http-proxy` or `https-proxy` are set, then they are configured with `snapd`.
This code was ported from [`snapcraft_legacy`](https://github.com/snapcore/snapcraft/blob/4a66b3b1b7e0cd39ba06dd4ab1c6d21c8cddd969/snapcraft_legacy/internal/build_providers/_base_provider.py#L510).
(CRAFT-1335)
=> buildd: set snapd http-proxy and https-proxy

craft_providers/bases/buildd.py, setup.py, tests/unit/bases/test_buildd.py
launchpad-buildd sets up some specialized configuration to stop snapd
from using the snap store's CDN when running in Canonical's production
build farm, since there are restrictions in place there on general
internet access but the non-CDN storage endpoint is always allowed.  If
this is in place, then we need to propagate it to containers we create.
I encountered this in an lpcraft build, but I think any of the *craft
tools could in principle hit the same problem when running in Launchpad.
launchpad-buildd normally passes HTTP proxy configuration allowing `snap
install` to work, but that doesn't necessarily apply to downloads
initiated by snapd itself, such as base snap downloads.
-----
=> buildd: Pass on snapd no-CDN configuration if set

craft_providers/actions/snap_installer.py, craft_providers/executor.py, craft_providers/lxd/lxd_instance.py, craft_providers/multipass/multipass_instance.py, tests/unit/actions/test_snap_installer.py
-----
Do not remove the previous snap file (i.e. `/tmp/<snap-name>.snap`) before pushing a new snap file into the instance.
Pushing a file into an instance overwrites the previous file, so there is no need to delete the previous file.
1. This isn't done in `snapcraft_legacy/internal/build_providers`
2. It doesn't need to be done
3. It adds time and complexity
(CRAFT-1370)
=> snap installer: do not remove previous snap file

craft_providers/actions/snap_installer.py, craft_providers/util/snap_cmd.py, tests/integration/actions/test_snap_installer.py, tests/integration/conftest.py, tests/unit/actions/test_snap_installer.py, tests/unit/util/test_snap_cmd.py
-----
Minor refactor of `snap_installer`.
https://github.com/canonical/craft-providers/pull/151 needs to be reviewed and merged before this PR.
No functional changes.  This is laying groundwork for the next PR to assert snaps.
Notable changes:
1. New integration test to inject a dangerously installed snap
2. Change `get_host_snap_revision()` to a generic function `get_host_snap_info()`, since I'll soon be needing more data than just the revision.
---
CRAFT-1371
=> snap installer: refactor

craft_providers/actions/snap_installer.py, craft_providers/util/snap_cmd.py, tests/unit/actions/test_snap_installer.py, tests/unit/util/test_snap_cmd.py
-----
Assert signed snaps injected into a provider.
If a snap on the host is signed (not dangerous), then craft-providers will:
1. collect the assertions from the host with `snap known`
2. push the assertions to the instance
3. add the assertions in the instance with `snap ack`
If the snap is unsigned on the host, then the snap is installed dangerously in the instance.  This behavior is unchanged.
The implementation in [snapcraft_legacy](https://github.com/snapcore/snapcraft/blob/433a09262443d645acbae5204b5c9a44433f4b83/snapcraft_legacy/internal/build_providers/_snap.py) was used as a reference.
I tested this manually with snapcraft, switching between dangerous and non-dangerous snaps.  The integration tests here already test for both scenarios too (I added those tests in the [previous …
=> snap installer: assert injected snaps

craft_providers/executor.py, craft_providers/lxd/lxd_instance.py, tests/integration/lxd/test_lxd_instance.py, tests/unit/conftest.py, tests/unit/lxd/test_lxd_instance.py
-----
Add `mount()` method to base Executor class.  This is required so applications can use these functions in the child classes.  This is similar to https://github.com/canonical/craft-providers/pull/140.
LXD's mount method was renamed to make room for new inherited `mount` method while still allowing access to the old method.
`LXDInstance.mount(host_source, target, device_name)` is now `LXDInstance.mount_with_device_name(host_source, target, device_name)`
None of the *craft applications use the `device_name` parameter, so there should be no impact.  
First usage will be in [rockcraft](https://github.com/canonical/rockcraft/pull/82).
(CRAFT-1383)
=> executor: add mount method to base Executor class

craft_providers/actions/snap_installer.py, tests/unit/actions/test_snap_installer.py
-----
Adds another assertion when injecting a snap into a provider.
@tigarmo and I saw this problem with revision 309 of rockcraft.  The snap's publisher was unverified and produced the error:
```
error: cannot assert: assert failed: cannot resolve prerequisite assertion: account (pMLNwd28ezFdozetvrAOlLj3UqC9HKpe)
```
Looking into `rockcraft`'s snap info, it contains a publisher with a matching account id:
```
'publisher': {
'id': 'pMLNwd28ezFdozetvrAOlLj3UqC9HKpe',
'username': 'sergiusens',
'display-name': 'Sergio Schvezov',
'validation': 'unproven'
}
```
I assume the key `'validation': 'unproven'` is causing the error.
To resolve this, `craft-providers` now collects the publisher account with `snap known account account-id=pMLNwd28ezFdozetvrAOlLj3UqC9HKpe`
The assertion looks like this: …
=> snap installer: get assertion for the publisher's account id

craft_providers/executor.py, tests/unit/conftest.py
-----
Add `is_running()` method to base Executor class. 
Needed for this PR: https://github.com/canonical/craft-providers/pull/163
=> executor: add `is_running()` method to base Executor class

craft_providers/__init__.py, craft_providers/lxd/__init__.py, craft_providers/lxd/lxd_provider.py, craft_providers/multipass/__init__.py, craft_providers/multipass/multipass_provider.py, craft_providers/provider.py, tests/integration/lxd/test_lxd_provider.py, tests/integration/multipass/test_multipass_provider.py, tests/unit/lxd/test_lxd_provider.py, tests/unit/multipass/test_multipass_provider.py, tests/unit/test_provider.py
-----
Add Provider, LXDProvider, and MultipassProvider classes.
These classes are near-duplicates of the classes in rockcraft (links for [provider](https://github.com/canonical/rockcraft/blob/4cfd6c8bac0b112127d420c8a3a1c6b0f3033ab5/rockcraft/providers/_provider.py), [lxd](https://github.com/canonical/rockcraft/blob/4cfd6c8bac0b112127d420c8a3a1c6b0f3033ab5/rockcraft/providers/_lxd.py), and [multipass](https://github.com/canonical/rockcraft/blob/4cfd6c8bac0b112127d420c8a3a1c6b0f3033ab5/rockcraft/providers/_multipass.py))
There are a few minor differences:
1. changes to `import` statements and `__init__.py` files
2. Simplified error handling in methods `ensure_provider_is_available()` and `launched_environment()`
- For example, there is no need to catch a `LXDError` and raise a …
=> providers: add Provider, LXDProvider, and MultipassProvider classes

craft_providers/executor.py, craft_providers/util/temp_paths.py, tests/unit/test_executor.py
-----
Multipass has access to the user's home directory, but not to arbitrary directories (e.g. `/mnt/`) due to snap confinement. Files pulled from an executor need to be stored in the home directory.
source: https://forum.snapcraft.io/t/call-for-testing-snapcraft-7-2-0/32171/10
=> executor: store temporary files in the home directory

craft_providers/lxd/lxc.py, tests/integration/lxd/test_lxc.py, tests/unit/lxd/test_lxc.py
-----
Add `copy()` to LXC class to make a copy of an instance.
(CRAFT-1479)
=> lxd: add lxc.copy() method to copy instances

tests/unit/lxd/test_launcher.py
-----
The unit tests in tests/unit/lxd/test_launcher.py were designed to work with a single instance.  They use fixtures that do not distinguish which calls are made to which instance.
This is preventing me from testing https://github.com/canonical/craft-providers/pull/177, where I need the tests to distinguish between and instance and a base instance.
This PR refactors the fixtures and does a little cleanup.
(CRAFT-1478)
=> tests: refactor lxd launcher tests

craft_providers/lxd/lxc.py
-----
Removed a TODO for support snapshots for `lxc.copy()`.  The lxc launch mechanism will not use snapshots, so this no longer needs to be implemented.
(CRAFT-1340)
=> lxc: remove TODO for copying snapshots

craft_providers/lxd/launcher.py, tests/integration/lxd/test_launcher.py, tests/unit/lxd/test_launcher.py
-----
Cache a configured LXD environment as an instance instead of an image.
On the first run of an application, an instance will be launched from an image (i.e. an image from https://cloud-images.ubuntu.com). The instance is then setup. After setup, a copy of this instance is saved (or cached) as a 'base instance'. 
This is done to reduce setup time on subsequent runs. When the application requests a new instance on a subsequent run, the base instance will be copied to create the new instance. This instance is run through a small subset of the setup, which is referred to as 'warmup'.
The flowchart below describes the logic inside the `launch()` call.  The flowchart has become crowded as it's evolved - it's a result of the fixed drawing size in Google Doc's embedded drawings.
- …
=> lxd: launch instances from local instance instead of image

.github/workflows/tests.yaml
-----
Minor CI change to support the OneFlow workflow and align with [other craft workflows](https://github.com/snapcore/snapcraft/blob/31a3990c8f42eb27c326e42b7a79619996ab456d/.github/workflows/tests.yaml#L2).
The GitHub CI workflow runs on all pull requests.
Additionally, it runs when pushing to any OneFlow branch beginning with `release/` or `hotfix/`.
=> ci: run workflow on all pull requests and oneflow branches

craft_providers/lxd/launcher.py, tests/integration/lxd/test_launcher.py, tests/integration/lxd/test_lxc.py, tests/unit/lxd/test_launcher.py
-----
Minor cleanup prior to adding support for expiring base instance.
- Add more assertions for lxd launcher to ensure the base instance mechanism is working.
- Mock `is_valid()` function
- Add an integration test for `lxc.info()`
- Clarify an error message
=> tests: improve lxd launcher tests for base instances

craft_providers/bases/buildd.py, craft_providers/bases/errors.py, tests/unit/bases/test_buildd.py
This PR supersedes #176 because of permissions to land it.
=> buildd: check internet after network command fails (CRAFT-1461)

craft_providers/lxd/launcher.py, setup.py, tests/integration/lxd/test_launcher.py, tests/unit/lxd/test_launcher.py
-----
To keep build environments clean, consistent, and up-to-date, any base instance older than 3 months (90 days) is deleted and recreated.
(CRAFT-1342)
=> lxd: delete and recreate invalid bases instances

craft_providers/multipass/multipass.py, craft_providers/multipass/multipass_instance.py, tests/unit/multipass/test_multipass_instance.py
-----
The method `push_file_io()` fails when it executes inside a working directory that the `ubuntu` user does not have access to. This scenario can occur after *craft applications mount the host's working directory to /root/project.
This minor defect was a side effect of the release of Multipass v1.10.0.  (see [release notes](https://github.com/canonical/multipass/releases/tag/v1.10.0) and [updated documentation](https://multipass.run/docs/exec-command)).
The change itself is small.  The PR is mostly docstrings and comments.
(CRAFT-1544)
=> MultipassInstance: `push_file_io()` method works regardless of working dir

craft_providers/lxd/launcher.py, craft_providers/lxd/lxd_instance.py, tests/unit/lxd/test_launcher.py
-----
The id map for LXD instances needs to be set after an instance is launched from an image or after copying from a base instance.
(CRAFT-1577)
=> lxd: set instance id map after launching or copying an instance

pyproject.toml, tests/integration/lxd/test_installer.py, tests/integration/lxd/test_launcher.py, tests/integration/multipass/test_installer.py, tests/unit/bases/test_buildd.py, tests/unit/conftest.py, tests/unit/lxd/test_lxd_instance.py
-----
I made some linter changes that have been bothering me:
- Remove useless pylint suppression with `useless-suppression` check.
- Minor reformats to combat `black`'s habit to split lines
All pedantic changes, nothing functional.  For example, I prefer to change:
```
return subprocess.run(  # pylint: disable=subprocess-run-check
final_cmd, **kwargs
)
```
to
```
return subprocess.run(final_cmd, **kwargs)
```
=> lint: enable pylint useless-supression, minor reformatting

craft_providers/lxd/launcher.py, craft_providers/lxd/lxd_provider.py, tests/unit/lxd/test_lxd_provider.py
-----
Minor PR to use the new `use_base_instance` parameter when launching LXD instances.
=> lxd: use new `use_base_instance` parameter

craft_providers/lxd/lxc.py, tests/integration/lxd/test_lxc.py, tests/unit/lxd/test_lxc.py
-----
This method allows for retrieving the value of a single key in a LXD instance's config key/value store.
It's required to unblock [this TODO](https://github.com/canonical/craft-providers/blob/fd238327501662014bb0df76ed468de4c2e7bee9/craft_providers/lxd/launcher.py#L219) for CRAFT-1576.
=> lxc: add new method `config_get()`

craft_providers/lxd/lxc.py, tests/unit/lxd/test_lxc.py
-----
No functional changes.
1. Add default for private method `run_lxd()`'s parameter `check=True` .  I did this because all calls to this method were setting `check=True`.
2. Reformat calls to `_run_lxc()` to improve readability
=> lxd: add default for _run_lxc() parameter `check=True`

craft_providers/lxd/launcher.py, tests/integration/lxd/test_launcher.py, tests/unit/lxd/test_launcher.py
-----
If an existing instance has a mismatched id map, either the instance will be auto-cleaned or a `BaseCompatibiltyError` will be raised.
(CRAFT-1576)
=> lxd: check id map when launching an existing instance

craft_providers/bases/buildd.py, craft_providers/lxd/lxd_provider.py, craft_providers/multipass/multipass.py, craft_providers/multipass/multipass_provider.py, tests/integration/conftest.py, tests/unit/bases/test_buildd.py, tests/unit/conftest.py, tests/unit/lxd/test_lxd_instance.py, tests/unit/multipass/test_multipass_instance.py, tests/unit/util/test_env_cmd.py
-----
It's been a busy 12 hours for the world of Python linting!
2 commits, 1 for the [latest `black` release](https://github.com/psf/black/releases/tag/23.1.0) and 1 for the [latest `pylint` release](https://github.com/PyCQA/pylint/releases/tag/v2.16.0).
Targeting `hotfix/1.7` so I can prep a craft-providers release.  I will have to post another PR targeting `main` to allow development on the `main` branch to continue.
=> lint: fixes for black and pylint

craft_providers/multipass/multipass.py, tests/integration/multipass/conftest.py, tests/unit/multipass/test_multipass.py
-----
Resolving the Multipass deprecation notice:
```
warning: "--mem" long option will be deprecated in favour of "--memory" in a future release.Please update any scripts, etc.
```
Waiting on https://github.com/canonical/craft-providers/pull/130
=> multipass: replace deprecated parameter `--mem` with `--memory`

craft_providers/bases/buildd.py, craft_providers/lxd/__init__.py, craft_providers/lxd/errors.py, craft_providers/lxd/lxd_provider.py, craft_providers/lxd/remotes.py, craft_providers/multipass/multipass_provider.py, tests/integration/lxd/test_lxd_provider.py, tests/integration/lxd/test_remotes.py, tests/unit/bases/test_buildd.py, tests/unit/lxd/test_errors.py, tests/unit/lxd/test_lxd_provider.py, tests/unit/lxd/test_remotes.py
-----
This PR adds support for interim and devel Ubuntu releases with LXD.
Broken into 6 separate commits to speed up review time.
Previously, craft-providers maintained a list of valid LXD images with a simple enum.  Now, the `remotes.py` module has a new dataclass called `RemoteImage` and a dictionary of valid `RemoteImages` to track what images are supported.
It is designed in such a way that users can add custom remotes and we'll be able to add support for other bases (like a centos base) without breaking changes.
For applications using the `LxdProvider` class (snapcraft, charmcraft, and rockcraft), there are no changes in behavior or usage.  You can simply pass in the new release names:
```python
class BuilddBaseAlias(enum.Enum):
XENIAL = "16.04"
BIONIC = "18.04"
FOCAL = "20.04" …
```
=> lxd: add support for interim Ubuntu releases

craft_providers/base.py, craft_providers/bases/buildd.py, craft_providers/bases/instance_config.py, tests/integration/lxd/test_launcher.py, tests/integration/multipass/test_launch.py, tests/unit/bases/test_buildd.py, tests/unit/bases/test_instance_config.py, tests/unit/lxd/test_lxd_provider.py, tests/unit/multipass/test_multipass_provider.py
-----
If craft-providers is interrupted while setting up an instance, the instance will be discarded on the next execution.
Broken into 5 discrete commits.
The implementation is pretty straightforward, using the instance's instance configuration file:
```python
def setup():
def warmup():
```
Previously, craft-providers did not track if an instance was fully setup.  If the set up was interrupted, the next execution of craft-providers would assume the instance was setup.  This causes a whole suite of hard-to-troubleshoot failures (e.g. apt packages can't be installed, no internet connectivity, snapd not configured).
This is similar to what is done for snapcraft's [core18|20 build providers](https://github.com/snapcore/snapcraft/blob/5b0d370ed00a689dbc3754291605830f1a270329/snapcraft_legacy/i …
=> bases(buildd): track if instance is properly setup

craft_providers/lxd/launcher.py, craft_providers/lxd/lxd_provider.py, tests/integration/lxd/test_launcher.py, tests/unit/lxd/test_launcher.py, tests/unit/lxd/test_lxd_provider.py
-----
A fairly innocuous PR to expire unstable base instances every 14 days.
1. `launch()` takes a new parameter `expiration` to set a base instance's expiration date.
- Previously, it was hardcoded to 90 days.
2. The `LXDProvider` class sets a 90 day expiration for stable images and a 14 day expiration for unstable images.
This is preparatory work for adding `BuilddBaseAlias.DEVEL` (CRAFT-1636).
=> lxd(LXDProvider): expire unstable base instances every 14 days

craft_providers/bases/buildd.py, craft_providers/lxd/remotes.py, craft_providers/multipass/multipass_provider.py, tests/integration/lxd/test_launcher.py, tests/unit/bases/test_buildd.py, tests/unit/lxd/test_remotes.py, tests/unit/multipass/test_multipass_provider.py
-----
- Add support for `BuilddBaseAlias.DEVEL`.
- Update `/etc/apt/sources.list` and `/etc/apt/sources.list.d/*.list` to point to the `devel` archives
(CRAFT-1636)
=> bases(buildd): add new BuilddBaseAlias.DEVEL

.bumpversion.cfg, craft_providers/__init__.py, docs/changelog.rst, docs/conf.py, setup.py
-----
`v1.8.1` will allow for snapcraft to use `devel` images.
=> Bump version: 1.8.0 → 1.8.1

craft_providers/lxd/lxd_provider.py, craft_providers/multipass/multipass_provider.py, craft_providers/provider.py
-----
Adding a new parameter from `LXDProvider` to the `Provider` base class and the `Multipass` class.
Multipass is currently not using the parameter, but it will use it in a PR next week!
=> provider: add `allow_unstable` to Provider base class

craft_providers/bases/buildd.py, tests/unit/bases/test_buildd.py
-----
When using a buildd base, `/etc/cloud/cloud.cfg` must be updated to prevent `/etc/apt/sources.list` from being reset when copying an instance.
This fixes an issue uncovered by https://github.com/snapcore/snapcraft/pull/4068
=> bases(buildd): update cloud.cfg to not reset apt's sources.list

craft_providers/lxd/launcher.py, tests/integration/lxd/test_launcher.py, tests/unit/lxd/test_launcher.py
This allows other *craft to get info of the LXD instance versions.
=> lxd: set image description to instance full name

craft_providers/lxd/remotes.py, craft_providers/multipass/__init__.py, craft_providers/multipass/multipass_provider.py, tests/integration/multipass/test_launch.py, tests/integration/multipass/test_multipass_provider.py, tests/unit/multipass/test_multipass_provider.py
-----
1. Add support for `kinetic`, `lunar`, and `devel` for Multipass with a new `RemoteImage` class.
2. Check if Multipass image are stable and use the `allow_unstable` parameter.
Split into 4 commits for your reviewing pleasure!
(CRAFT-1637)
=> multipass(MultipassProvider): support kinetic, lunar, and devel images

craft_providers/base.py, craft_providers/bases/__init__.py, craft_providers/lxd/lxd_provider.py, craft_providers/lxd/remotes.py, craft_providers/multipass/multipass_provider.py, craft_providers/provider.py, tests/integration/lxd/test_lxd_provider.py, tests/integration/lxd/test_remotes.py, tests/integration/multipass/test_multipass_provider.py, tests/unit/bases/test_get_base.py, tests/unit/lxd/test_lxd_provider.py, tests/unit/lxd/test_remotes.py, tests/unit/multipass/test_multipass_provider.py
We are now use `base_configuration` which included alias to decide which os / version to use, instead of use `build_base`. The `build_base` now has no effect.
Added 2 new functions in craft_providers.bases:
`get_base_alias()` accept a tuple `(system, version)` and return a `BaseAlias`.
`get_base_from_alias` accept a `BaseAlias` and return the `Base` of it.
-----
=> provider: deprecate build_base

craft_providers/base.py, craft_providers/bases/__init__.py, craft_providers/bases/centos.py, craft_providers/lxd/remotes.py, tests/integration/lxd/test_lxd_provider.py, tests/unit/bases/test_centos_7.py
Request Ubuntu 18.04 for cgroup v1 support
The image will pull CentOS image from LXD images servers.
Enable epel-release and centos-release-scl repos, and install backported python 3.8.
Python 3.8 will be the default python 3 interpreter.
All packages will be updated after bootstrapping finished.
CRAFT-1696
=> bases: add CentOS 7 support

craft_providers/bases/__init__.py, craft_providers/lxd/remotes.py, tests/unit/bases/test_get_base.py, tests/unit/lxd/test_remotes.py
=> bases: apply stricter typing to base names.

.github/workflows/tests.yaml, craft_providers/multipass/installer.py, tests/unit/multipass/test_installer.py
-----
Reorganize github CI tests and workaround failing MacOS integration tests.
1. Separate linters, unit tests, and integration tests
2. Align with starbase's [workflow](https://github.com/canonical/starbase/blob/main/.github/workflows/tests.yaml) (this PR is a first step, not the end result)
3. Add more unit testing across OS's and Python versions 
(CRAFT-1726)
=> ci: reorganize github CI tests

craft_providers/base.py, craft_providers/bases/almalinux.py, craft_providers/bases/centos.py, craft_providers/bases/ubuntu.py, tests/unit/bases/test_almalinux.py, tests/unit/bases/test_centos_7.py, tests/unit/bases/test_ubuntu_buildd.py
All images will be pre-installed with `build-essential` (or equivalent), `git`, and `python3` (with `devel`, `pip`, `venv`, `setuptools`, `wheel`)
=> bases: pre-installation of common packages

craft_providers/bases/almalinux.py, craft_providers/bases/centos.py, craft_providers/bases/ubuntu.py
Packages that are cached locally are usually never used again. Clean them up to reduce size and increase speed of copying snapshots
=> bases: clean up packages cache

.github/workflows/tests.yaml, Makefile, craft_providers/actions/snap_installer.py, craft_providers/base.py, craft_providers/bases/centos.py, craft_providers/lxd/launcher.py, craft_providers/lxd/lxc.py, craft_providers/lxd/remotes.py, craft_providers/multipass/multipass.py, craft_providers/util/os_release.py, pyproject.toml, setup.cfg, setup.py, tests/integration/conftest.py, tests/unit/actions/test_snap_installer.py, tests/unit/bases/test_almalinux.py, tests/unit/bases/test_centos_7.py, tests/unit/bases/test_ubuntu_buildd.py, tests/unit/conftest.py, tests/unit/lxd/test_launcher.py, tests/unit/lxd/test_lxc.py, tests/unit/util/test_os_release.py
-----
To separate code changes from tooling changes, I ignored many `ruff` rules.  These will be addressed in subsequent PRs.  See https://github.com/canonical/craft-providers/issues/287
(CRAFT-1726)
=> lint: add ruff, remove autoflake, flake8, isort, pydocstyle, pylint

craft_providers/actions/snap_installer.py, craft_providers/lxd/lxd_instance.py, pyproject.toml, tests/integration/lxd/test_lxc.py
-----
Resolves:
- `PLC1901`: `string == ""` can be simplified to `not string` as an empty string is falsey
=> lint: fix ruff warning PLC1901

craft_providers/multipass/multipass_provider.py, tests/integration/multipass/test_multipass_provider.py
-----
Lunar is now available as a stable interim release.
Only the latest interim release is available on MacOS, so kinetic is not tested.
=> multipass(MultipassProvider): update image for lunar

.github/workflows/tests.yaml, craft_providers/multipass/_launch.py, craft_providers/util/os_release.py, tests/integration/actions/test_snap_installer.py, tests/integration/conftest.py, tests/integration/lxd/conftest.py, tests/integration/lxd/test_launcher.py, tests/integration/lxd/test_lxc.py, tests/integration/multipass/conftest.py, tests/integration/multipass/test_launch.py, tests/integration/multipass/test_multipass_instance.py, tests/unit/bases/test_ubuntu_buildd.py, tests/unit/lxd/test_lxd_instance.py, tests/unit/multipass/test_multipass.py, tests/unit/multipass/test_multipass_instance.py, tests/unit/multipass/test_multipass_provider.py, tests/unit/util/test_os_release.py
-----
Welcome to the future!
Changes:
- Use `ubuntu-latest` runner
- Use `lxd` on `latest/stable`
- Use `core22` for tests and examples
- Remove `core16` tests
I need to get this done before moving to `tox`, as there is a strange error occurring with `core20` images + a `20.04` runner + lxd `4.0` (likely due to the ordering of tests). 
Resolves https://github.com/canonical/craft-providers/issues/270 and related to https://github.com/canonical/craft-providers/pull/278
(CRAFT-1726)
=> tests: test with core22 by default, remove core16 tests

craft_providers/base.py, craft_providers/lxd/launcher.py, craft_providers/lxd/lxd_provider.py, craft_providers/multipass/_launch.py, pyproject.toml
-----
Resolves: 
- `SIM108`: Use ternary operator instead of `if`-`else`-block
- `SIM112`: Use capitalized environment variable `HTTPS_PROXY` instead of `https_proxy`
- `SIM117`: Use a single `with` statement with multiple contexts instead of nested `with` statements
- `TRY300`: Consider moving this statement to an `else` block
=> lint: fix ruff warnings SIM108, SIM112, SIM117, TRY300

.github/workflows/tests.yaml, HACKING.rst, README.rst
-----
Add ssh access to runners in the CI workflow using [action-tmate](https://github.com/marketplace/actions/debugging-with-tmate).
This is to live permanently in the workflow. It can be triggered by enabling debug when running an action, so no code changes or test branches are needed.
If it is useful, I can upstream the workflow changes to `starbase`.
This PR requires a leap of faith -  we need to merge the PR and then confirm it works as expected.  It worked great on my own fork, so I expect it will work here.
Resolves https://github.com/canonical/craft-providers/issues/311
=> ci: add permanent ssh access to github runners

.github/workflows/tests.yaml, craft_providers/multipass/multipass_provider.py, setup.py, tests/integration/multipass/test_multipass_provider.py
-----
> :warning: Do not squash
In preparation for #337, which is a hotfix for `1.10`, this PR cherry-picks two commits for `1.10` and add 3 more commits to keep CI working.
(CRAFT-1767)
=> hotfix: backport fixes to 1.10

craft_providers/lxd/launcher.py, tests/integration/lxd/test_launcher.py, tests/unit/lxd/test_launcher.py
-----
When copying from a base instance, set the hostname of the instance.
This is a replacement for #337, where I thought that hostnames would be self-managed.  That is only the case for images with `cloud-init` configured and buildd images do not have `cloud-init` :sob: 
I also decided not to "clear" (remove) the base instance hostname.  It led to unpredictable behavior the next time I tried to set it.
(CRAFT-1767)
=> lxd: set hostname after copying from a base instance

craft_providers/lxd/lxd_provider.py, craft_providers/multipass/multipass_provider.py, craft_providers/provider.py, tests/unit/lxd/test_lxd_provider.py, tests/unit/multipass/test_multipass_provider.py
-----
Add a `name` and `install_recommendation` property to `Provider` classes.
This can be used in places like [this](https://github.com/canonical/charmcraft/blob/4b34df89d55e545513d8a1b5ac7b84e443541565/charmcraft/providers.py#L219)
Resolves #166 
(CRAFT-1474)
=> providers: add name and install recommendation properties

craft_providers/actions/snap_installer.py, craft_providers/lxd/launcher.py, craft_providers/lxd/lxd_instance.py, tests/integration/actions/test_snap_installer.py, tests/unit/lxd/test_launcher.py
This commit does two things:
- Update almost all instances of log.warning() to log.debug() in lxd- related code. The rationale is that the majority of those messages are meant to assist developers in debugging/troubleshooting, and not really meant for end-users.
- Add a couple of log.info() messages. These are only a couple on purpose, as the intent is to provide a _bit_ more information during instance fetching/setup without overwhelming the end-user with info that is ultimately not relevant to them ("implementation details"). For example, we say that we're "Starting the instance" but not that we are "Configuring networking". Since the debug messages are preserved, the information is ultimately still available in logfiles.
Note that multipass code still needs to be updated.
Fixes #377 …
=> lxd: update logging semantics

craft_providers/base.py, tests/integration/lxd/test_launcher.py, tests/integration/multipass/test_launch.py, tests/unit/actions/test_snap_installer.py, tests/unit/bases/test_almalinux.py, tests/unit/bases/test_centos_7.py, tests/unit/bases/test_instance_config.py, tests/unit/bases/test_ubuntu_buildd.py, tests/unit/lxd/test_launcher.py, tests/unit/lxd/test_lxd_provider.py, tests/unit/multipass/test_multipass_provider.py
-----
- Replace `snap set system refresh.hold=<24h>` with `snap refresh --hold`
- Execute this call only during `setup` instead of `setup` and `warmup`
- Bump compatibility tag
This required moving a few other snapd-related calls to only execute during `setup`. 
In `craft-providers<1.13.0`, these snapd calls were [only made once](https://github.com/canonical/craft-providers/blob/3ea09344578f03a458676fac51784bbe6ea7f305/craft_providers/bases/ubuntu.py#L378-L379) during `setup`.  During the [base refactor](https://github.com/canonical/craft-providers/pull/274) in `1.13.0`, these calls were made during `setup` and `warmup`.  I've reverted to the previous behavior because it works, speeds up warmup, and is a neat and tidy way to make this change.
Compatibility tag bump is in a separate commit …
=> bases: use `snap refresh --hold`

craft_providers/lxd/launcher.py, craft_providers/lxd/lxc.py, craft_providers/lxd/lxd_instance.py, craft_providers/lxd/lxd_instance_status.py, tests/integration/lxd/test_launcher.py, tests/unit/lxd/test_launcher.py, tests/unit/lxd/test_lxc.py, tests/unit/lxd/test_lxd_instance.py
Use `user.craft_providers.status` and `user.craft_providers.timer` in LXD to detect current status to avoid race
that try to create same instance from different process.
Also added restart() to instance to avoid ephemeral delete it when stop for configuration.
Fixes #341
=> lxc: create status data in lxd to avoid race

.github/workflows/release-publish.yaml
-----
Disable pypi autopublishing.  It hasn't worked anyways because there hasn't been a pypi token in github.
=> ci: disable auto-publish to pypi

.readthedocs.yaml
-----
The docs were failing to build when creating an epub and pdf of the docs.
You should now be able to see a link to readthedocs as one of the CI jobs in this PR.
=> chore(docs): disable epub and pdf creation

README.rst
-----
A badge to indicate if the docs are building.
Preview here: https://github.com/canonical/craft-providers/tree/docs-update#readme
And yes, the docs are indeed failing to build.
=> docs(readme): add readthedocs build badge

.github/renovate.json5
-----
Renovate has not been working because `branchConcurrentLimit` was implicitly set to `prConcurrentLimit`.  This caused each branch to be "yellow" and renovate would refuse to open a PR.
```
DEBUG: Calculating branchConcurrentLimit (2)
DEBUG: 4 already existing branches found: renovate/doc-dependencies,renovate/dev-dependencies,renovate/major-github-actions,renovate/ruff
DEBUG: Branch concurrent limit remaining: 0
DEBUG: Calculated maximum branches remaining this run: 0
DEBUG: Branches limit = 0
```
When `prConcurrentLimit` is not set, the default for `branchConcurrentLimit` is 10.  I raised it to 20 because we already have 8 `packageRules` groups and it's not unreasonable that one of our repos could have 10 renovate branches.
=> ci(renovate): allow more branches and PRs

.github/workflows/tests.yaml
-----
Another weekend has passed with no Renovate PRs!
Following [this advice](https://github.com/renovatebot/renovate/discussions/22590#discussioncomment-6097210), tests run by default on renovate branches.
Order of failing events:
1. Renovate created/rebased the [`renovate/ruff`](https://github.com/canonical/craft-providers/tree/renovate/ruff) branch
2. No github tests run on renovate branches
3. An internal renovate test runs, but this does not count as a test because `internalChecksAsSuccess=False` (this was a recent [breaking change](https://github.com/renovatebot/renovate/releases/tag/35.0.0))
4. Renovate does not open the PR because [`prCreation = not-pending`](https://docs.renovatebot.com/configuration-options/#prcreation) because its waiting for a test to run
=> ci(renovate): run tests on renovate branches

craft_providers/executor.py, craft_providers/lxd/lxc.py, craft_providers/lxd/lxd_instance.py, craft_providers/multipass/multipass.py, craft_providers/multipass/multipass_instance.py, tests/unit/conftest.py, tests/unit/lxd/test_lxd_instance.py, tests/unit/multipass/test_multipass_instance.py
-----
For calls to `subprocess.run`, the default `check=False` was used or `check` was passed via `kwargs`.
Ruff 0.0.291 is now warning that this implicit behavior is a [poor practice](https://pycodequ.al/docs/pylint-messages/w1510-subprocess-run-check.html):
```
tox:lint-ruff
lint-ruff: commands[0]> ruff check --respect-gitignore .
tests/unit/conftest.py:96:16: PLW1510 `subprocess.run` without explicit `check` argument
```
Backward compatible.
This issue was raised by #408
=> feat: add check parameter to execute_run

craft_providers/lxd/launcher.py, tests/unit/lxd/test_launcher.py
Fix another code path that may copy unfinshed base instance.
Fix: https://github.com/canonical/craft-providers/issues/412
CRAFT-2076
=> fix(lxd): check another path before use base instance

.github/workflows/tests.yaml
-----
Removing the android sdk and libraries doubles available disk space from ~14GB to ~28GB.  I chose this one because it's easy to remove and a big one.  This should be enough disk space for the foreseeable future.
Unblocks #330.  (I tested on top of #330 and the CI [passed](https://github.com/canonical/craft-providers/actions/runs/6591827692/job/17913377570?pr=431)).
=> ci: clean disk on github runners

.github/CODEOWNERS
-----
This reverts https://github.com/canonical/craft-providers/pull/425. 
The codeowners feature is a nuisance - it automatically sends review requests, even when the author is not ready for a PR review.
=> ci(github): remove starcraft team as codeowners

craft_providers/lxd/installer.py, tests/integration/lxd/test_installer.py, tests/unit/lxd/test_installer.py
-----
When checking if lxd is initialized, require the default lxd profile to contain a disk device with a path of `/`.
https://github.com/canonical/craft-providers/issues/429
(CRAFT-2174)
=> fix: require disk device in default lxd profile

craft_providers/actions/snap_installer.py, tests/unit/actions/test_snap_installer.py
Also reuse the base when inject other snaps.
=> feat(snaps): inject base snap from host

.github/workflows/docs.yaml, .github/workflows/tests.yaml
-----
Colorize the output of tox in Github CI.  
Tox does not colorize its output in Github because of the envvar `TERM` is set to `dumb`.  However, github handles colorized output quite nicely.
[Before](https://github.com/canonical/craft-providers/actions/runs/6672145538/job/18135507099#step:6:1)
[After](https://github.com/canonical/craft-providers/actions/runs/6733840789/job/18303418705?pr=442#step:6:1)
=> ci: colorize tox output

.github/workflows/tests.yaml
-----
Currently, we run 4 integration tests on Linux runners, each for a different version of python.
Often, 1 flaky test will fail and cause all 4 jobs to be canceled.  This is time-consuming for the developer and uses a lot more runners than needed.
=> ci(github): disable fast failure for integration tests

craft_providers/lxd/launcher.py, craft_providers/lxd/lxc.py, craft_providers/lxd/lxd_instance.py, tests/integration/lxd/test_lxc.py, tests/integration/lxd/test_lxd_instance.py, tests/unit/lxd/test_launcher.py, tests/unit/lxd/test_lxc.py, tests/unit/lxd/test_lxd_instance.py
-----
The PID of the process that creates an instance is stored in the instance's LXD config and is used when launching an instance.
The `is_valid()` check for base instances now ensures an instance is stopped and has been fully setup.  If another process is busy launching and setting up the base instance, then `is_valid()` will wait (and eventually time out).  If the process that launched the base instance is inactive, then the instance is auto-cleaned (deleted and recreated).
This last statement has a slight behavioral change.  Previously, craft-providers raised a generic error (`Instance setup failed. Check LXD logs for more details`) and required the user to delete the base instance manually.  Now, the bad base instance will be auto-cleaned.  I think this is OK because this aligns …
=> feat(lxd): store and check PID when launching instances

docs/changelog.rst
-----
Even though the PID check is a new feature, we decided to make this a patch release since it fixes a bug where improperly setup base instances were not being cleaned.
=> docs(changelog): add 1.20.1 release notes

.github/renovate.json5, pyproject.toml
We can't update these because of requests-unixsocket
-----
=> ci(deps): prevent renovate from updating types-requests or urllib3

craft_providers/bases/__init__.py, craft_providers/bases/ubuntu.py, craft_providers/lxd/remotes.py, craft_providers/multipass/multipass_provider.py, tests/integration/multipass/test_multipass_provider.py
-----
Noble is open for development and all images are now published, all tooling is required to support noble ahead of noble release to actually release noble.
Add Noble as supported base, to be able to build & ship noble.
=> feat(buildd): add support for ubuntu 24.04

craft_providers/bases/__init__.py, craft_providers/bases/ubuntu.py, craft_providers/lxd/remotes.py, craft_providers/multipass/multipass_provider.py, tests/unit/lxd/test_remotes.py
-----
Lunar is EOL'd as of January 2024.
=> chore: drop lunar (ubuntu 23.04)

craft_providers/base.py, tests/integration/lxd/test_launcher.py, tests/integration/multipass/test_launch.py, tests/unit/bases/test_almalinux.py, tests/unit/bases/test_centos_7.py, tests/unit/bases/test_ubuntu_buildd.py, tests/unit/test_base.py
-----
In preparation for releasing 1.21.0.
The compatibility tag has to be updated because of a confusing order of events.  The compat tag was bumped to `v4` on `main`  then later bumped to `v5` in a hotfix branch and merged into main:
```
1.19.3 (2023-12-01)
-------------------
- Update base compatibility tag to ``base-v5``.
...
1.20.1 (2023-11-30)
-------------------
- Update base compatibility tag to ``base-v4``
```
This bump to `v6` is to prevent a scenario where a user upgrades from `1.19.3` to `1.21.0` and gets the changes from `1.20.0` but doesn't get a new compat tag.
=> chore(bases): bump compatibility tag to v6

craft_providers/multipass/multipass_provider.py
-----
This is the last image I needed to point to `buildd` in preparation for `core24`.
I'll cut a craft-providers release after this.
=> feat: update multipass noble image

craft_providers/base.py, tests/integration/lxd/test_launcher.py, tests/integration/multipass/test_launch.py, tests/unit/bases/test_almalinux.py, tests/unit/bases/test_centos_7.py, tests/unit/bases/test_ubuntu_buildd.py, tests/unit/test_base.py
-----
Bumping compat tag because some image sources have changed from `ubuntu` to `buildd`.
=> chore(bases): bump compatibility tag to v7

craft_providers/bases/ubuntu.py, tests/unit/bases/test_ubuntu_buildd.py
-----
Set the same environment variables as [craft-parts](https://github.com/canonical/craft-parts/blob/c11570597d4a397aba1744fa08adcd344682246e/craft_parts/packages/deb.py#L488) to ensure packages are installed non-interactively.
Source: https://matrix.to/#/!GGqzbFAUQprdPgYYCM:ubuntu.com/$yww83UdJUJtcD5mURgNA9K1xD9oMrscyZ5HaNqJoU6s?via=ubuntu.com&via=matrix.org&via=gnulinux.club
=> fix(ubuntu): ensure apt installs are non-interactive

.github/workflows/tests.yaml
-----
We renamed `platform` to `os` but forgot to change the artifact names.
Pre-req for https://github.com/canonical/craft-providers/pull/497
=> ci: fix artifact names

craft_providers/lxd/lxd.py, tests/unit/lxd/test_lxd.py
-----
Cherry-pick #532 to `hotfix/1.20` for snapcraft 7.x
=> fix(lxd): update LXD version naming support LTS (#532)

docs/.custom_wordlist.txt, docs/changelog.rst
-----
This release is intended for snapcraft 7.x.  The integration tests will fail to launch almalinux 9, but that's OK because snapcraft doesn't use alma.
=> docs(changelog): add 1.20.2 release notes

craft_providers/base.py, craft_providers/lxd/launcher.py, docs/changelog.rst, tests/integration/lxd/test_launcher.py, tests/integration/multipass/test_launch.py, tests/unit/bases/test_almalinux.py, tests/unit/bases/test_centos_7.py, tests/unit/bases/test_ubuntu_buildd.py, tests/unit/lxd/test_launcher.py, tests/unit/test_base.py
-----
This is ready so we can do a rebase.
=> Changes for 1.20.3

tests/integration/lxd/test_lxd_provider.py
-----
See https://discourse.ubuntu.com/t/new-lxd-image-server-available-images-lxd-canonical-com/43824
Fixes #502
=> tests: re-enable alma linux integration tests

docs/changelog.rst
=> chore(merge): '1.20.3' into 'main'

craft_providers/lxd/installer.py, craft_providers/lxd/lxc.py, pyproject.toml, tests/unit/lxd/test_installer.py
Check if the lxd snap is installed by querying the snapd socket
instead of looking for an executable in the path, as lxd can use
auto-installer stubs.
-----
=> fix: check if lxd snap is installed

craft_providers/errors.py, docs/explanation/index.rst
=> chore: point to correct readthedocs docs

tests/integration/lxd/conftest.py, tests/integration/lxd/test_lxd_provider.py, tests/integration/lxd/test_remotes.py
-----
Disable 24.10 tests due to #598.
Long-term failures are common in craft-providers, so I added some fixturing to make this easier to maintain.
Similar to https://github.com/canonical/snapcraft/pull/4922
Fixes #593
(CRAFT-3104)
=> tests: disable 24.10 integration tests

craft_providers/bases/__init__.py, craft_providers/bases/ubuntu.py, craft_providers/lxd/remotes.py, craft_providers/multipass/multipass_provider.py, tests/integration/multipass/test_multipass_provider.py, tests/unit/lxd/test_remotes.py
-----
Ubuntu 23.10 reached end of life on 2024-Jul-11.
=> chore: drop Ubuntu 23.10 (Mantic)

craft_providers/multipass/multipass_provider.py
-----
Use the buildd daily image for 24.04 for the Noble alias with Multipass
Fixes #511
Source: https://matrix.to/#/!GGqzbFAUQprdPgYYCM:ubuntu.com/$222ie8jdhmvzWbHqDyXE8QPgPtr4dUSph0J9T4pD6Xc?via=ubuntu.com&via=matrix.org&via=kde.org
=> fix(multipass): use Ubuntu 24.04 image

.github/workflows/tests.yaml, HACKING.rst, pyproject.toml, tox.ini
-----
This replaces a frozen version of ruff from pip with the latest snap of ruff, helping us dogfood our own ecosystem.
=> build(deps): use the ruff snap

tests/integration/lxd/test_lxc.py
-----
This was failing intermittently yesterday and consistently failing today, so this error message probably changed in a progressive release of the LXD snap.
The alternative is to drop this test - craft-providers doesn't need to test an invalid LXD operation as an integration test.
=> tests: update LXD error message

craft_providers/bases/__init__.py, craft_providers/bases/ubuntu.py, craft_providers/lxd/remotes.py, craft_providers/multipass/_launch.py, craft_providers/multipass/multipass.py, craft_providers/multipass/multipass_provider.py, tests/integration/lxd/conftest.py, tests/integration/lxd/test_lxc.py, tests/integration/lxd/test_lxd_provider.py, tests/integration/lxd/test_remotes.py, tests/integration/multipass/test_basic.py, tests/integration/multipass/test_multipass_provider.py, tests/unit/lxd/test_remotes.py, tests/unit/multipass/test_launch.py
-----
Require Multipass>=`1.14.1` for launching Ubuntu 24.04 (Noble).  
Previously, Multipass had been using the `snapcraft:devel` alias for 24.04 images (#602).  This worked until last month when the `devel` alias started pointing to `24.10` images.
Once Multipass `1.14.1` is released to `latest/stable` and to homebrew, this can be reverted and the minimum Multipass version will be bumped to `1.14.1` (#638).
Fixes #628
(CRAFT-3270)
=> fix: require multipass>=1.14.1 for Ubuntu 24.04 (Noble)

craft_providers/lxd/lxc.py, craft_providers/lxd/lxd_instance.py, pyproject.toml, tests/integration/lxd/test_lxc.py, tests/unit/lxd/test_lxc.py, tests/unit/lxd/test_lxd_instance.py
=> Get Pro status in managed LXD instance

craft_providers/lxd/lxc.py, craft_providers/lxd/lxd_instance.py, tests/integration/lxd/test_lxc.py, tests/unit/lxd/test_lxc.py, tests/unit/lxd/test_lxd_instance.py
-----
This is a part of a series of adding Pro features to craft libraries.
This PR adds the functionality of enabling a single Pro service on a managed LXD instance.
=> feat: enabled pro services on managed LXD instance

.github/workflows/tests.yaml, craft_providers/bases/__init__.py, craft_providers/bases/ubuntu.py, craft_providers/lxd/remotes.py, craft_providers/multipass/multipass_provider.py, docs/changelog.rst, pyproject.toml, tests/integration/lxd/test_lxc.py, tests/integration/multipass/test_multipass_provider.py, tests/unit/lxd/test_remotes.py
-----
This backports the `requests-unixsocket2` change to 1.20, which is used by both Snapcraft 7 and Charmcraft 2
=> build(deps): replace requests-unixsocket with requests-unixsocket2

craft_providers/actions/snap_installer.py, docs/reference/changelog.rst, pyproject.toml, tests/unit/actions/test_snap_installer.py
-----
Use the snap name when getting a [declaration assertion](https://ubuntu.com/core/docs/reference/assertions/snap-declaration) from snapd.
Unblocks https://github.com/canonical/snapcraft/issues/4683
Unblocks https://github.com/canonical/snapcraft/issues/4927
Unblocks https://github.com/canonical/charmcraft/issues/1770
Fixes #622 
(CRAFT-3259)
(CRAFT-3351)
=> fix: get assertions for aliased snaps

docs/reference/changelog.rst
-----
Release notes for 2.0.4.
Waiting on https://github.com/canonical/craft-providers/pull/674 to land first.
=> docs(changelog): add 2.0.4 release notes

docs/index.rst, pyproject.toml
-----
Use the new grid template from canonical-sphinx.
=> build(deps): bump canonical-sphinx to 0.2.0

craft_providers/lxd/lxc.py, craft_providers/lxd/lxd_instance.py, docs/index.rst, pyproject.toml, tests/integration/lxd/test_lxc.py, tests/unit/lxd/test_lxc.py, tests/unit/lxd/test_lxd_instance.py
-----
Intsall Ubuntu Pro Client inside the managed LXD instance, which is necessary for all Pro-related commands such as attach, enable, etc.
=> feat: install Ubuntu Pro Client in LXD instance

craft_providers/multipass/_launch.py, craft_providers/multipass/multipass.py, docs/.wordlist.txt, docs/reference/changelog.rst, tests/integration/multipass/test_basic.py, tests/unit/multipass/test_launch.py, tests/unit/multipass/test_multipass.py
-----
Multipass 1.14.1 has been released so we can bump the minimum version.
Fixes #638 
(CRAFT-3308)
=> chore: require multipass>=1.14.1

.github/workflows/tests.yaml
-----
`ubuntu-latest` is being migrated to 24.04 this month.  Seems like LXD is no longer installed by default.
I took the liberty to test lxd on `candidate` while touching this.
source: https://github.com/canonical/craft-providers/pull/701
=> ci: install lxd from candidate channel, install lxd on ubuntu 24.04

craft_providers/executor.py, craft_providers/lxd/lxd_instance.py, craft_providers/multipass/multipass_instance.py, docs/reference/changelog.rst, tests/unit/lxd/test_lxd_instance.py, tests/unit/multipass/test_multipass_instance.py, tests/unit/test_executor.py
-----
Normalizes names when creating a Multipass instance.
Uses the same normalization function as LXD.
Unblocks https://github.com/canonical/charmcraft/issues/2058
Fixes #226 
(CRAFT-3883)
=> fix: use Multipass-compatible instance names

craft_providers/hookutil.py, tests/integration/test_hookutil.py, tests/unit/test_hookutil.py
-----
Applications using craft-providers may inadvertently leave around lxc instances, either when new base instances supersede old ones, or when the application is uninstalled.  Add a module implementing logic that applications can use in configure and remove snap hooks to prune these unneeded lxc instances.
=> feat: upstream snap hooks

craft_providers/lxd/lxd_instance.py, craft_providers/lxd/lxd_provider.py, docs/reference/changelog.rst, tests/unit/lxd/test_lxd_provider.py
-----
Allow `craft-application`'s `ProviderService` to dis/allow intercepting `mknod` calls in LXD.
https://github.com/canonical/craft-application/pull/607
=> feat: mknod intercepts now configurable from LXDProvider

craft_providers/lxd/launcher.py, craft_providers/lxd/lxc.py, craft_providers/lxd/lxd_instance.py, craft_providers/lxd/lxd_instance_status.py, docs/reference/changelog.rst, tests/unit/lxd/test_launcher.py, tests/unit/lxd/test_lxc.py, tests/unit/lxd/test_lxd_instance.py
-----
Waits for LXD instances to start, restart, or stop before returning.  This is necessary because `lxc [start|restart|stop]` is asynchronous - the call may return before the operation completes. 
This can cause a race condition between Craft Providers calling `lxc start` then `lxc file pull` and the instance completing startup.  
I did some internal refactoring to make this cleaner to implement, so I recommend reviewing per-commit.
Fixes #719
(CRAFT-4048)
=> fix(lxd): wait for instance to start and stop

craft_providers/bases/__init__.py, craft_providers/bases/ubuntu.py, craft_providers/lxd/lxc.py, craft_providers/lxd/remotes.py, craft_providers/multipass/multipass_provider.py, docs/reference/changelog.rst, tests/integration/lxd/conftest.py, tests/unit/lxd/test_lxc.py, tests/unit/lxd/test_remotes.py
-----
* Re-enables devel tests now that `devel` images are working with LXD.
* Fixes a new race condition where LXD reports a new state when an instance is launched.
* Add Ubuntu 25.04 (Plucky)
Fixes #729
Fixes #731
Fixes #734
=> check if instance is starting, re-enable devel tests, add plucky

.github/workflows/tics.yaml, Makefile, pyproject.toml, tox.ini
-----
Needs to be merged to see if it works.
The `setup-tics` and `test-coverage` targets are used by starflow's upstream TICS workflow. To more easily adopt full "uv-ification" later, this PR adds a dummy makefile for those two targets and puts the "actual" commands into the tox configuration file.
`tox -f tics` appears to have an identical output to `make test-coverage` in other repositories, so this "should" work.
CRAFT-4536
=> ci: add tics workflow

Makefile, pyproject.toml, tox.ini
-----
Includes three fixes for the TICS CI: install tox in CI, use the correct project name, don't parallelize coverage (this breaks reporting)
=> fix(ci): install tox in ci

.github/workflows/cla-check.yaml
---
A longer term fix is to use full policy checker from starflow, but this is a quick fix that should unblock https://github.com/canonical/craft-providers/pull/777.
=> ci: update cla check

craft_providers/lxd/installer.py
Currently, the lxd crafting provider assumes lxd is installed as snap, by only checking the socket path in `/var/snap`.
With this patch, the non-snap default socket path is tried first.
Maybe, as a follow-up, one should just check if `lxc` or `lxd` work properly, instead of hardcoding path names.
---
=> fix: check lxd availability for non-snap socket path
